
## Feature Reduction Techniques and Classification Algorithms

## Introduction

 A classification dataset was taken from kaggle. The data was splited into training and testing splits in the ratio of 75-25. And done the Feature scaling,Feature reduction using LDA & SVD techniques and 2 separate train-test datasets were created.
Then we have done the classification using SVM, Naive Bayes and Decision tree Classifier on each of the datasets and analyzed the performance of each Feature reduction technique.

## Dataset Information

Age : Age of the patient

Sex : Sex of the patient

exang: exercise induced angina (1 = yes; 0 = no)

ca: number of major vessels (0-3)

cp : Chest Pain type chest pain type

     Value 1: typical angina
     Value 2: atypical angina
     Value 3: non-anginal pain
     Value 4: asymptomatic
     
trtbps : resting blood pressure (in mm Hg)

chol : cholestoral in mg/dl fetched via BMI sensor

fbs : (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)

rest_ecg : resting electrocardiographic results

     Value 0: normal
     Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
     Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
     
thalach : maximum heart rate achieved

target : 0= less chance of heart attack 1= more chance of heart attack

Source of Dataset : https://www.kaggle.com/rashikrahmanpritom/heart-attack-analysis-prediction-dataset/version/2

## Importing Dataset

In [2]:
import numpy as np
import pandas as pd
import io
import seaborn as sns

In [3]:
df=pd.read_csv("heart.csv")
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

## Training and Testing Split 

In [5]:
y=df['output']
X=df.drop('output',axis=1)

In [6]:
y


0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25)


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Feature Reduction

## LDA

In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=1)
X_train_LDA = lda.fit_transform(X_train, y_train)
X_test_LDA = lda.transform(X_test)
print(X_train_LDA)

[[ 0.08593333]
 [ 0.23750317]
 [ 1.1940922 ]
 [-1.75518528]
 [ 1.19290052]
 [-0.47941993]
 [-0.40013573]
 [ 1.8152307 ]
 [ 1.75679975]
 [ 0.28190278]
 [ 0.81065362]
 [ 0.7806153 ]
 [ 0.2541623 ]
 [-1.68960873]
 [ 0.11818149]
 [-0.28354652]
 [-0.71897787]
 [ 2.73849006]
 [-0.99738259]
 [ 1.86293722]
 [-0.53372459]
 [ 2.30038552]
 [-0.81044737]
 [ 0.05775104]
 [ 0.84302093]
 [ 0.42398117]
 [ 1.04417593]
 [-0.55813274]
 [-1.5952368 ]
 [ 1.38710881]
 [-1.35376471]
 [-0.88051032]
 [-0.98678134]
 [-1.59073319]
 [-1.08534537]
 [ 0.10903911]
 [-1.78921795]
 [-2.21024269]
 [-0.04537219]
 [ 0.12859921]
 [ 1.01851401]
 [ 1.81293166]
 [ 0.76943359]
 [ 0.79023402]
 [-1.86641641]
 [ 2.13127559]
 [ 0.08593333]
 [-0.80799383]
 [-0.89474952]
 [-1.15836132]
 [ 2.84178738]
 [ 2.00602359]
 [-0.90288144]
 [-1.62720643]
 [-1.75491025]
 [-0.29734553]
 [-1.15542374]
 [-2.33984711]
 [-0.10590159]
 [ 0.09649261]
 [ 1.38846183]
 [ 1.11770936]
 [-1.37300706]
 [ 1.11323046]
 [-2.40156295]
 [ 1.63474277]
 [-2.01740

## SVD

In [11]:
from sklearn.decomposition import TruncatedSVD
svd=TruncatedSVD(n_components=2)
X_train_SVD=svd.fit_transform(X_train, y_train)
X_test_SVD=svd.transform(X_test)
print(X_train_SVD)

[[-1.72389241 -0.59315437]
 [ 0.85237996  0.16911935]
 [ 1.20897279  0.02505063]
 [-1.76803878  0.91143217]
 [ 1.50100779 -0.36887742]
 [-1.09874666 -1.01869223]
 [-0.1101495  -0.33865477]
 [ 1.58822009 -1.42399161]
 [ 2.60343485  0.49706666]
 [-0.26889927 -0.5487417 ]
 [ 1.48942379  0.81450867]
 [ 0.85633694 -1.093867  ]
 [ 0.25079964 -1.12851505]
 [-2.63816121 -0.96378846]
 [ 0.2741611   0.5302131 ]
 [-0.51968644  0.11298807]
 [-1.11534017  0.04643128]
 [ 2.96826708 -0.99053415]
 [-0.61238884  1.83344232]
 [ 1.32840484  1.04213853]
 [ 0.30825838 -0.68423634]
 [ 3.46767998 -0.1814942 ]
 [-0.50790327 -0.42298922]
 [ 1.066805    0.50764469]
 [-0.16831572  0.5383415 ]
 [-0.36323583 -1.34657041]
 [ 1.32204471 -1.7996061 ]
 [-0.8277126   1.37736469]
 [-1.93501161  0.02309595]
 [ 1.03298983 -0.85700366]
 [-2.33167964 -1.02007808]
 [-0.70723413  1.39869286]
 [-1.42188493 -0.01335645]
 [-2.20855348 -0.87431756]
 [-1.34879929  0.84368566]
 [-0.03595796 -0.36099482]
 [-1.89516677 -0.13215526]
 

## SVM Using LDA


In [15]:
from sklearn.svm import SVC
model_svm_lda=SVC(kernel='linear')
model_svm_lda.fit(X_train_LDA, y_train)
y_pred=model_svm_lda.predict(X_test_LDA)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix SVM using LDA")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


Confusion Matrix SVM using LDA
[[27  9]
 [ 4 36]]
              precision    recall  f1-score   support

           0       0.87      0.75      0.81        36
           1       0.80      0.90      0.85        40

    accuracy                           0.83        76
   macro avg       0.84      0.82      0.83        76
weighted avg       0.83      0.83      0.83        76



## SVM Using SVD


In [16]:
from sklearn.svm import SVC
model_svm_svd=SVC(kernel='linear')
model_svm_svd.fit(X_train_SVD, y_train)
y_pred=model_svm_svd.predict(X_test_SVD)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix SVM using SVD")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


Confusion Matrix SVM using SVD
[[26 10]
 [ 2 38]]
              precision    recall  f1-score   support

           0       0.93      0.72      0.81        36
           1       0.79      0.95      0.86        40

    accuracy                           0.84        76
   macro avg       0.86      0.84      0.84        76
weighted avg       0.86      0.84      0.84        76



## Naive Bayes Using LDA


In [17]:
from sklearn.naive_bayes import GaussianNB 
model_nb_lda=GaussianNB()
model_nb_lda.fit(X_train_LDA, y_train)
y_pred=model_nb_lda.predict(X_test_LDA)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix Naive Bayes Using LDA")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix Naive Bayes Using LDA
[[27  9]
 [ 4 36]]
              precision    recall  f1-score   support

           0       0.87      0.75      0.81        36
           1       0.80      0.90      0.85        40

    accuracy                           0.83        76
   macro avg       0.84      0.82      0.83        76
weighted avg       0.83      0.83      0.83        76



## Naive Bayes Using SVD

In [18]:
from sklearn.naive_bayes import GaussianNB 
model_nb_svd=GaussianNB()
model_nb_svd.fit(X_train_SVD, y_train)
y_pred=model_nb_svd.predict(X_test_SVD)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix Naive Bayes Using LDA")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix Naive Bayes Using LDA
[[24 12]
 [ 4 36]]
              precision    recall  f1-score   support

           0       0.86      0.67      0.75        36
           1       0.75      0.90      0.82        40

    accuracy                           0.79        76
   macro avg       0.80      0.78      0.78        76
weighted avg       0.80      0.79      0.79        76



## Decision Tree Using LDA

In [19]:
from sklearn.tree import DecisionTreeClassifier
model_dt_lda=DecisionTreeClassifier(random_state=np.random)
model_dt_lda.fit(X_train_LDA, y_train)
y_pred=model_dt_lda.predict(X_test_LDA)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix Decision Tree Using LDA")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix Decision Tree Using LDA
[[27  9]
 [ 5 35]]
              precision    recall  f1-score   support

           0       0.84      0.75      0.79        36
           1       0.80      0.88      0.83        40

    accuracy                           0.82        76
   macro avg       0.82      0.81      0.81        76
weighted avg       0.82      0.82      0.81        76



## Decision Tree Using SVD

In [20]:
from sklearn.tree import DecisionTreeClassifier
model_dt_svd=DecisionTreeClassifier(random_state=np.random)
model_dt_svd.fit(X_train_SVD, y_train)
y_pred=model_dt_svd.predict(X_test_SVD)

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix Decision Tree Using SVD")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix Decision Tree Using SVD
[[23 13]
 [ 7 33]]
              precision    recall  f1-score   support

           0       0.77      0.64      0.70        36
           1       0.72      0.82      0.77        40

    accuracy                           0.74        76
   macro avg       0.74      0.73      0.73        76
weighted avg       0.74      0.74      0.73        76



# Inference

Accuracy can be a good measure to evaluate all the algorithhms or models and Feature reduction techniques.

Analysis on Feature Reduction Techniques: LDA performs better than SVD for Naive Bayes and Decision Tree and for SVM SVD performs slightly better i.e. 1% more accurate than LDA. As LDA creates maximize the separation between the 2 classes while SVD tries to make maximum variability between the new features.

Analysis on Classification Algorithms: Performance of all the algorithms (SVM,Naive Bayes & Decision tree) have almost similar accuracy depending upon the feature reductoin technique while SVM using SVD performs slightly better by 1 % for dataset on which LDA is applied.